eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: zhanglujie
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useSSL=false&characterEncoding=utf-8
env: 
  dev-4
girl:
  name: lili-666
  age: 2
