spring:
  datasource:
    url: mysql:jdbc://127.0.0.1:3306/springcloud?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    password: zhanglujie
    username: root
  redis:
    host: localhost
    port: 6379
